export const ADD_BOOK_TO_CART = "ADD_BOOK_TO_CART"
export const DELETE_BOOK_FROM_CART = "DELETE_BOOK_FROM_CART"
export const LOGIN_USER = "LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const GET_BOOKS = "GET_BOOKS"
export const GET_AUTHORS = "GET_AUTHORS"
export const GET_PUBLISHERS = "GET_PUBLISHERS"
export const GET_CATEGORIES = "GET_CATEGORIES"

