export const GET_CART = "GET_CART"
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"
export const GET_CART_FAILURE = "GET_CART_FAILURE"
export const ADD_BOOK_TO_CART = "ADD_BOOK_TO_CART"
export const DELETE_BOOK_FROM_CART = "DELETE_BOOK_FROM_CART"
export const INCREASE_BOOK_AMOUNT_IN_CART = "INCREASE_BOOK_AMOUNT_IN_CART"
export const DECREASE_BOOK_AMOUNT_IN_CART = "DECREASE_BOOK_AMOUNT_IN_CART"
export const CART_ACTION_FAILURE = "CART_ACTION_FAILURE"
export const CLEAR_CART = "CLEAR_CART"

export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL"
export const LOGIN_FAILED = "LOGIN_FAILED"
export const LOGOUT_USER = "LOGOUT_USER"

export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_SUCCESSFUL = "REGISTER_SUCCESSFUL"
export const REGISTER_FAILED = "REGISTER_FAILED"


export const GET_BOOKS = "GET_BOOKS"
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS"
export const GET_BOOKS_FAILURE = "GET_BOOKS_FAILURE"

export const GET_AUTHORS = "GET_AUTHORS"
export const GET_AUTHORS_SUCCESS = "GET_AUTHORS_SUCCESS"
export const GET_AUTHORS_FAILURE = "GET_AUTHORS_FAILURE"

export const GET_PUBLISHERS = "GET_PUBLISHERS"
export const GET_PUBLISHERS_SUCCESS = "GET_PUBLISHERS_SUCCESS"
export const GET_PUBLISHERS_FAILURE = "GET_PUBLISHERS_FAILURE"

export const GET_CATEGORIES = "GET_CATEGORIES"
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE"

